name: ci

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6
      - uses: https://codeberg.org/mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: zig build test
